### ISSUE TITLE
Issue with sql server builds

### ISSUE THREAD

**Issue by strangetobefree** [rovats/waltz-docker#18]
I can't seem to get this to build with sql server. the original pom for waltz requires a local install of sqljdbc4 but the same trick doesn't seem to work here for some reason.

I have tried multiple times to get docker build to work and installed the file in my local repo using 
mvn install:install-file -Dfile=sqljdbc4.jar -Dpackaging=jar -DgroupId=com.microsoft.sqlserver -DartifactId=sqljdbc4 -Dversion=4.0

Not sure if there is something i the dependencies i am missing?

**Comment by rovats** [comment]
Hi Steve,

You won't need to install any dependencies locally when using this tool, you don't even need maven installed.
Please can you let me know more details about your setup? Are you using docker desktop on Windows?

Also which command does this fail on?

**Comment by strangetobefree** [comment]
hi Rohit,

thanks for the response, sorry for my late reply,

I thought that i did because i needed a local maven repo for JOOQ pro? at any rate the real issue is that at the docker build step here the build breaks whatever I do.

[ERROR] Failed to execute goal on project waltz-common: Could not resolve dependencies for project com.khartec:waltz-common:jar:1.0-SNAPSHOT: Could not find artifact com.microsoft.sqlserver:sqljdbc4:jar:4.0 in central (https://repo.maven.ap           ache.org/maven2) 

running this command 
docker build --tag waltz-build:latest --build-arg maven_profiles=waltz-mssql,dev-mssql --build-arg jooq_pro_version=3.13.2 -f build/build.Dockerfile .

i've tried local installs of the jar from clojars, repointing the repository manually, but whatever I do it breaks at this step.

I'm fairly sure it is something obvious but no luck so far. 

Kind Regards,

Steve

**Comment by strangetobefree** [comment]
it might be worth mentioning that I am off on holiday next week so might be a little slow to respond! back on 4th jan

**Comment by rovats** [comment]
Hi Steve,

Please can you try using `waltz-mssql-alt` profile instead of `waltz-mssql`? 
`maven_profiles=waltz-mssql-alt,dev-mssql`
This uses newer JDBC drivers which should work fine.

And also for jOOQ pro, you won't need a local maven repo, you can just download jOOQ Pro and place it in the appropriate directory, and the tool will install them automatically on the build container's local maven repo.

Instructions here: https://github.com/rovats/waltz-docker#mssql

**Comment by strangetobefree** [comment]
I'll have a look and let you know how it goes when i get back, thanks for your help rohit

**Comment by strangetobefree** [comment]
hi rohit, thanks this worked. i have a developer coming in next week for a couple of weeks just to tidy this all up so i might get him to reach out. i think I might submit a change to the original repo changing the profiles around as there isn't much reason to use the  waltz-mssql profile and i can't see it working for anyone.

thanks again, hope you are ok

**Comment by rovats** [comment]
Hi Steve,

No problem, great that you've got it working.
Yep, happy to help out your Dev in case they get have any questions using this tool.

Regards,
Rohit
